version: '3'
services:
  # app:
  #   # build: .
  #   # image: ghcr.io/shunsukenonomura/my-app:latest
  #   tty: true

  app:
    build: 
      context: .
      dockerfile: docker/dev/Dockerfile
    working_dir: '/root/volume'
    tty: true
    volumes:
      - ./volume:/root/volume
    ports:
      - 8000:8000
    extra_hosts: # linux環境の場合にhost.docker.internalでhost上にアクセスするために必要
      - "host.docker.internal:host-gateway"
    command: poetry run uvicorn app.main:app --reload --host=0.0.0.0
