# gh pagesの更新
name: Build Version gh pages

on:
  push:
    branches-ignore:
      - gh-pages
    tags:
      - 'v*'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    # 環境準備
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.11"

    - name: Install Poetry
      run: |
        curl -sSL https://install.python-poetry.org | python3 -
      env:
        POETRY_HOME: /opt/poetry

    - name: Add Poetry to PATH
      run: echo "PATH=$PATH:/opt/poetry/bin" >> $GITHUB_ENV

    - name: Install dependencies with Poetry
      working-directory: ./app/volume
      run: |
        poetry install --no-root

    # 出力設定
    - name: Set output path from ref
      id: vars
      run: |
        if [[ "${GITHUB_REF}" == refs/heads/* ]]; then
          name="${GITHUB_REF#refs/heads/}"
        elif [[ "${GITHUB_REF}" == refs/tags/* ]]; then
          name="${GITHUB_REF#refs/tags/}"
        else
          name="unknown"
        fi
        echo "output=versions/${name}" >> "$GITHUB_OUTPUT"

    # redocビルド
    - name: Build ReDoc
      working-directory: ./app/volume
      run: |
        set -o allexport
        source ../.env_dev
        set +o allexport
        poetry run python build_redoc.py

    # pytest cov ビルド
    - name: Run Pytest and generate coverage report
      working-directory: ./app/volume
      run: |
        set -o allexport
        source ../.env_dev
        set +o allexport
        poetry run python3 ./migrate.py
        poetry run pytest --cov=app -v --cov-report=html

    # MkDocs 用 Poetry インストール
    - name: Install docs dependencies
      working-directory: ./docs/volume
      run: poetry install --no-root

    # MkDocs サイトビルド
    - name: Build MkDocs site
      working-directory: ./docs/volume
      run: poetry run mkdocs build

    # pushファイル統合
    - name: Prepare deploy directory
      run: |
        mkdir -p tmp_deploy/redoc
        mkdir -p tmp_deploy/htmlcov
        mkdir -p tmp_deploy/site
        cp -r app/volume/docs/backend/* tmp_deploy/redoc/
        cp -r app/volume/htmlcov/* tmp_deploy/htmlcov/
        cp -r docs/volume/site/* tmp_deploy/site/


    # push
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: tmp_deploy # 出力先ディレクトリ
        publish_branch: gh-pages
        destination_dir: ${{ steps.vars.outputs.output }}
        force_orphan: false


    # indexの更新
    - name: Checkout gh-pages
      run: |
        git fetch origin gh-pages
        git checkout gh-pages

    - name: Generate index.html
      run: bash ./generate-index.sh

    - name: Commit index.html
      run: |
        git config user.name "github-actions"
        git config user.email "github-actions@github.com"
        git add index.html
        git commit -m "update index.html"
        git push origin gh-pages