# .github/workflows/delete-version.yml
name: Delete version directory from gh-pages

on:
  workflow_dispatch:
    inputs:
      version_subpath:
        description: 'Subdirectory under versions/ to delete (e.g. feature/hoge or v1.0.0)'
        required: true

jobs:
  delete-version:
    runs-on: ubuntu-latest

    steps:
      # 不要なブランチ　もしくは　タグの削除
      - name: Attempt to delete both branch and tag refs
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          name="${{ github.event.inputs.version_subpath }}"

          echo "Attempting to delete branch: $name"
          gh api -X DELETE "repos/${{ github.repository }}/git/refs/heads/$name" || echo "No such branch"

          echo "Attempting to delete tag: $name"
          gh api -X DELETE "repos/${{ github.repository }}/git/refs/tags/$name" || echo "No such tag"

      # versionsドキュメントの削除
      - name: Checkout gh-pages branch
        uses: actions/checkout@v4
        with:
          ref: gh-pages

      - name: Set git user identity
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Delete directory
        run: |
          safe_path="versions/${{ github.event.inputs.version_subpath }}"
          echo "Deleting directory: $safe_path"
          git rm -r --ignore-unmatch "$safe_path" || echo "Directory not found"
          git commit -m "Remove $safe_path from gh-pages" || echo "Nothing to commit"
          git push origin gh-pages
