name: Generate index.html on gh-pages

on:
  push:
    branches:
      - gh-pages

jobs:
  update-index:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout gh-pages branch
        uses: actions/checkout@v4

      - name: Generate index.html
        run: |
          bash ./generate-index.sh

      - name: Commit and push index.html
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add index.html
          git commit -m "chore: update index.html"
          git push origin gh-pages