name: Build and Deploy ReDoc

on:
  push:
    branches-ignore:
      - gh-pages

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest


    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.11"

    - name: Install Poetry
      run: |
        curl -sSL https://install.python-poetry.org | python3 -
      env:
        POETRY_HOME: /opt/poetry

    - name: Add Poetry to PATH
      run: echo "PATH=$PATH:/opt/poetry/bin" >> $GITHUB_ENV

    - name: Install dependencies with Poetry
      working-directory: ./volume
      run: |
        poetry install --no-root

    - name: Get branch name and normalize
      id: vars
      run: |
        branch="${GITHUB_REF#refs/heads/}"
        safe_branch=$(echo "$branch" | sed 's#/#-#g')
        echo "branch=$safe_branch" >> $GITHUB_OUTPUT

    # github secretsに登録するほうがセキュリティ上良い
    - name: Build ReDoc
      working-directory: ./volume
      run: |
        set -o allexport
        source ../.env_dev
        set +o allexport
        poetry run python build_redoc.py

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: volume/docs/backend  # 出力先ディレクトリ
        publish_branch: gh-pages
        destination_dir: ${{ steps.vars.outputs.branch }}
        force_orphan: false
