name: Container Security Scan

on:
  workflow_dispatch:

jobs:
  trivy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@v0.13.1
        with:
          image-ref: 'ghcr.io/shunsukenonomura/my-app:latest'
          format: 'table'
          exit-code: '1'
          ignore-unfixed: true